/**
 * Which files of a repository make it into the universe.
 * Paths are repo-relative, '/'-separated, relative to the analyzed subdirectory.
 */

export const SOURCE_FILE = /\.(?:[cm]?ts|tsx|[cm]?js|jsx)$/i;
const DECLARATION_FILE = /\.d\.[cm]?ts$/i;
const CONFIG_FILE = /(?:^|\/)(?:tsconfig[^/]*\.json|jsconfig\.json|package\.json)$/;

/** Build output, dependencies and other non-authored code. Never included. */
const VENDOR_DIRS = new Set([
  'node_modules', 'bower_components', 'jspm_packages', '.git', '.github', '.next', '.nuxt', '.output',
  '.svelte-kit', '.turbo', '.vercel', '.cache', '.yarn', '.pnpm-store', 'dist', 'build', 'out', 'coverage',
  'vendor', 'vendors', 'third_party', 'third-party', 'public', 'static', 'storybook-static', 'tmp', 'temp',
  'compiled', 'precompiled', 'generated', '__generated__',
]);

/** Large secondary trees that drown the actual product code (analyze them via a subdirectory URL instead). */
const NOISE_DIRS = new Set([
  'examples', 'example', 'demo', 'demos', 'docs', 'doc', 'dev-docs', 'documentation', 'website', 'site', 'benchmarks',
  'benchmark', 'bench',
  'playground', 'playgrounds', 'sandbox', 'sandboxes', 'templates', 'starters',
]);

const TEST_DIRS = new Set([
  '__tests__', '__test__', 'test', 'tests', '__mocks__', '__fixtures__', 'fixtures', '__snapshots__', 'e2e',
  'cypress', 'playwright', 'spec', 'specs', 'testing', 'test-utils', '__testfixtures__', 'stories', '.storybook',
]);
const TEST_FILE = /\.(?:test|spec|e2e|stories|story|bench|cy|fixture)\.[cm]?[jt]sx?$/i;
const MINIFIED_NAME = /(?:[.-]min|[.-]bundle|\.umd|\.production|\.development|\.iife)\.[cm]?js$/i;

/** Hand-written giants exist (excalidraw App.tsx is ~450 KB); anything bigger is almost always generated. */
export const MAX_FILE_BYTES = 1200 * 1024;
export const MAX_CONFIG_BYTES = 256 * 1024;

export type FileClass = 'source' | 'config' | 'skip';

export function classifyPath(path: string, includeTests: boolean): FileClass {
  const segments = path.split('/');
  const fileName = segments[segments.length - 1];
  for (let i = 0; i < segments.length - 1; i++) {
    const dir = segments[i].toLowerCase();
    // Dot-directories are tooling (.github, .husky, .vscode, .idea…), never product code.
    if (dir.startsWith('.') || VENDOR_DIRS.has(dir) || NOISE_DIRS.has(dir)) return 'skip';
    if (!includeTests && TEST_DIRS.has(dir)) return 'skip';
  }
  if (CONFIG_FILE.test(path)) return 'config';
  if (!SOURCE_FILE.test(fileName) || DECLARATION_FILE.test(fileName)) return 'skip';
  if (MINIFIED_NAME.test(fileName)) return 'skip';
  if (!includeTests && TEST_FILE.test(fileName)) return 'skip';
  // Tool configuration (vite.config.ts, .eslintrc.js, Gulpfile.js…) is not part of the program.
  if (fileName.startsWith('.') || /[.-]config\.[cm]?[jt]s$/i.test(fileName) || /^(?:gulp|grunt|jake)file\./i.test(fileName)) {
    return 'skip';
  }
  return 'source';
}

/** Content sniffing for generated/minified code that slipped past the name checks. */
export function looksGenerated(text: string): boolean {
  const sample = text.length > 8192 ? text.slice(0, 8192) : text;
  let lines = 1;
  for (let i = 0; i < sample.length; i++) if (sample.charCodeAt(i) === 10) lines++;
  if (sample.length > 4000 && sample.length / lines > 400) return true;
  return /^\s*(?:\/\/|\/\*)[^\n]*(?:@generated|auto-generated|autogenerated|do not edit)/i.test(sample.slice(0, 400));
}

/**
 * When the repo has more source files than we can afford, keep the ones most
 * likely to be the core: shallow files in src-like directories first.
 */
export function rankForTruncation(path: string): number {
  const segments = path.split('/');
  let score = segments.length * 10;
  if (segments.some((s) => s === 'src' || s === 'lib' || s === 'app' || s === 'source' || s === 'core')) score -= 25;
  if (segments.some((s) => s === 'scripts' || s === 'tools' || s === 'internal' || s === 'legacy')) score += 15;
  return score;
}
